remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sciolus.github.io
description: A blog of breadth, not depth.

gem "github-pages", group: :jekyll_plugins
